// NORCET 10 — Stage I · 100 questions across 5 nursing sections

export const NORCET_META = {
  name: 'NORCET 10 — Stage I',
  shortName: 'NORCET 10',
  totalQuestions: 100,
  totalMarks: 100,
  duration: 90,
  correctMarks: 1,
  wrongMarks: -0.33,
  perSectionTime: 18,
  rollNo: '10024156',
  candidate: 'Anant Trivedi',
  centre: 'AIIMS New Delhi — Examination Hall 1',
  date: '15 June 2026',
}

const q = (id, text, a, b, c, d, correct, section) => ({
  id,
  text,
  options: [
    { id: 'A', text: a },
    { id: 'B', text: b },
    { id: 'C', text: c },
    { id: 'D', text: d },
  ],
  correct,
  topicName: section,
})

const MSN = 'Medical-Surgical Nursing'
const FON = 'Fundamentals of Nursing'
const CHN = 'Community Health Nursing'
const OBG = 'OBG & Midwifery'
const PDR = 'Paediatric Nursing'

export const NORCET_QUESTIONS = [
  // ── Section A: Medical-Surgical Nursing (Q1–Q20) ──
  q('nq1',  'The MOST common early complication of acute myocardial infarction is:', 'Cardiogenic shock', 'Heart failure', 'Arrhythmias', 'Ventricular rupture', 'C', MSN),
  q('nq2',  'Normal urine output per hour in a healthy adult is:', '10–20 mL', '20–30 mL', '30–50 mL', '50–100 mL', 'C', MSN),
  q('nq3',  'The antidote for heparin overdose is:', 'Vitamin K', 'Protamine sulfate', 'Fresh frozen plasma', 'Atropine sulfate', 'B', MSN),
  q('nq4',  'In COPD, the primary stimulus for breathing is:', 'Elevated PaCO₂', 'Decreased PaO₂ (hypoxic drive)', 'Decreased blood pH', 'Elevated serum bicarbonate', 'B', MSN),
  q('nq5',  "Trousseau's sign (carpopedal spasm with BP cuff inflation) is positive in:", 'Hypernatraemia', 'Hyperkalemia', 'Hypocalcaemia', 'Hypermagnesaemia', 'C', MSN),
  q('nq6',  "Cullen's sign (periumbilical bruising) is classically associated with:", 'Acute appendicitis', 'Acute pancreatitis', 'Acute cholecystitis', 'Liver abscess', 'B', MSN),
  q('nq7',  "Chvostek's sign is elicited by tapping over the:", 'Femoral nerve', 'Radial nerve', 'Facial nerve (CN VII)', 'Ulnar nerve', 'C', MSN),
  q('nq8',  'The recommended head-of-bed elevation for a patient with raised intracranial pressure is:', 'Flat (0°) supine', 'Trendelenburg position', '30–45° elevation', 'Right lateral decubitus', 'C', MSN),
  q('nq9',  'The Parkland formula is used for fluid resuscitation in:', 'Acute pancreatitis', 'Major thermal burns', 'Septic shock', 'Diabetic ketoacidosis', 'B', MSN),
  q('nq10', 'Peripheral IV potassium infusion should NEVER exceed:', '5 mEq/hr', '10 mEq/hr', '20 mEq/hr', '40 mEq/hr', 'B', MSN),
  q('nq11', 'The minimum and maximum scores on the Glasgow Coma Scale (GCS) are:', '0 and 14', '1 and 15', '3 and 15', '1 and 14', 'C', MSN),
  q('nq12', 'Dumping syndrome is a common complication after:', 'Colostomy', 'Gastrectomy', 'Colectomy', 'Appendectomy', 'B', MSN),
  q('nq13', 'Target INR range for a patient on warfarin therapy for atrial fibrillation:', '1.5–2.0', '2.0–3.0', '3.0–4.0', '0.8–1.2', 'B', MSN),
  q('nq14', "Kernig's sign is positive in:", 'Acute appendicitis', 'Bacterial meningitis', 'Peptic ulcer perforation', 'Pancreatitis', 'B', MSN),
  q('nq15', 'The FIRST-priority nursing action for a patient with suspected MI (per MONA):', 'Obtain 12-lead ECG', 'Establish IV access', 'Administer supplemental oxygen', 'Initiate cardiac monitoring', 'C', MSN),
  q('nq16', 'In diabetic ketoacidosis (DKA), the FIRST priority intervention is:', 'Insulin infusion', 'IV fluid resuscitation (0.9% NaCl)', 'Potassium replacement', 'Sodium bicarbonate administration', 'B', MSN),
  q('nq17', "McBurney's point tenderness is a classic sign of:", 'Cholecystitis', 'Acute appendicitis', 'Peptic ulcer', 'Renal colic', 'B', MSN),
  q('nq18', 'A patient with liver cirrhosis develops asterixis and confusion. This MOST likely indicates:', 'Hypoglycaemia', 'Hepatic encephalopathy', 'Hyponatraemia', "Wernicke's encephalopathy", 'B', MSN),
  q('nq19', "Raynaud's phenomenon is typically triggered by:", 'Exposure to heat only', 'Exposure to cold and/or emotional stress', 'Acute infection', 'High altitude exposure', 'B', MSN),
  q('nq20', 'The hallmark radiological finding of ARDS on chest X-ray is:', 'Unilateral pleural effusion', 'Bilateral diffuse infiltrates ("white-out")', 'Cardiomegaly', 'Pneumothorax', 'B', MSN),

  // ── Section B: Fundamentals of Nursing (Q21–Q40) ──
  q('nq21', "In Maslow's hierarchy of needs, which need takes HIGHEST priority in acute nursing care?", 'Safety and security', 'Love and belonging', 'Physiological needs', 'Self-esteem', 'C', FON),
  q('nq22', 'Normal resting respiratory rate in a healthy adult is:', '8–12 breaths/min', '12–20 breaths/min', '20–28 breaths/min', '28–36 breaths/min', 'B', FON),
  q('nq23', 'WHO recommends hand-washing with soap for a minimum of:', '10 seconds', '15 seconds', '20 seconds', '30 seconds', 'C', FON),
  q('nq24', 'The preferred IM injection site for infants and toddlers under 3 years of age is:', 'Dorsogluteal', 'Ventrogluteal', 'Vastus lateralis', 'Deltoid', 'C', FON),
  q('nq25', 'Normal oral body temperature in an adult is:', '35.5–36.0°C', '36.5–37.5°C', '37.5–38.0°C', '38.0–38.5°C', 'B', FON),
  q('nq26', 'Z-track technique in IM injection is used to:', 'Reduce injection pain at the site', 'Prevent medication from seeping into subcutaneous tissue', 'Ensure deeper muscle penetration', 'Prevent formation of haematoma', 'B', FON),
  q('nq27', "Head elevation in Semi-Fowler's position is:", '15–20°', '30–45°', '60–75°', '85–90°', 'B', FON),
  q('nq28', 'Normal resting pulse rate in a healthy adult is:', '40–60 bpm', '60–100 bpm', '100–120 bpm', '50–80 bpm', 'B', FON),
  q('nq29', 'Which of the following is NOT included in the "Seven Rights" of medication administration?', 'Right drug', 'Right dose', 'Right colour', 'Right route', 'C', FON),
  q('nq30', "Kübler-Ross's five stages of grief in the CORRECT order are:", 'Denial → Anger → Bargaining → Depression → Acceptance', 'Anger → Denial → Bargaining → Acceptance → Depression', 'Denial → Bargaining → Anger → Depression → Acceptance', 'Depression → Denial → Anger → Bargaining → Acceptance', 'A', FON),
  q('nq31', 'Norton Scale is used to assess the risk of:', 'Patient falls', 'Aspiration pneumonia', 'Pressure ulcer development', 'Malnutrition', 'C', FON),
  q('nq32', 'Which isolation precaution requires the nurse to wear an N95 respirator mask?', 'Contact precautions', 'Droplet precautions', 'Airborne precautions', 'Standard precautions', 'C', FON),
  q('nq33', 'The MOST reliable method to confirm nasogastric (NG) tube placement is:', 'Auscultation of air insufflation', 'pH testing of gastric aspirate', 'Chest X-ray confirmation', 'Observing for coughing or gagging', 'C', FON),
  q('nq34', 'The AVPU scale is used to assess:', 'Pain intensity', 'Level of consciousness', 'Nutritional status', 'Fall risk', 'B', FON),
  q('nq35', 'Normal serum sodium (Na⁺) level is:', '115–125 mEq/L', '125–135 mEq/L', '135–145 mEq/L', '145–155 mEq/L', 'C', FON),
  q('nq36', 'SBAR communication tool is primarily used for:', 'Patient documentation', 'Safe patient handover and clinical communication', 'Family health education', 'Medication verification', 'B', FON),
  q('nq37', 'The FIRST nursing action for a patient with blood pressure of 80/50 mmHg:', 'Repeat the blood pressure measurement', 'Notify the physician immediately', 'Place the patient in supine position', 'Start IV fluid resuscitation', 'C', FON),
  q('nq38', 'The PRIORITY nursing assessment for a patient receiving NG tube feeding is:', 'Monitoring skin integrity around the tube', 'Checking residual gastric volume before each feeding', 'Monitoring body weight daily', 'Checking blood glucose every 4 hours', 'B', FON),
  q('nq39', 'A nurse documents care BEFORE performing it. This violates which documentation principle?', 'Accuracy', 'Confidentiality', 'Factual and timely recording', 'Legibility', 'C', FON),
  q('nq40', 'On the Braden Scale for pressure ulcer risk, a LOWER score indicates:', 'Lower risk of pressure ulcer', 'Higher risk of pressure ulcer', 'No risk', 'Moderate risk only', 'B', FON),

  // ── Section C: Community Health Nursing (Q41–Q60) ──
  q('nq41', 'The Alma-Ata Declaration (1978) primarily focused on:', 'Maternal and child health only', 'Primary health care for all people', 'Control of infectious diseases', 'Nutritional supplementation programmes', 'B', CHN),
  q('nq42', 'Primary prevention BEST describes:', 'Treatment of existing disease', 'Early diagnosis and screening', 'Health promotion and specific protection', 'Rehabilitation after illness', 'C', CHN),
  q('nq43', 'Herd immunity is generally achieved when immunization coverage reaches:', 'At least 50% of the population', 'At least 60% of the population', 'At least 70% of the population', 'At least 80–85% of the population', 'D', CHN),
  q('nq44', 'Recommended temperature for cold chain maintenance of most EPI vaccines is:', '−20 to −15°C', '2–8°C', '8–12°C', '0–2°C', 'B', CHN),
  q('nq45', 'DOTS strategy is used for management of:', 'Malaria', 'HIV/AIDS', 'Tuberculosis', 'Hepatitis B', 'C', CHN),
  q('nq46', 'Oral Polio Vaccine (OPV) is stored at:', '2–8°C', '−20°C or below', 'Room temperature', '8–15°C', 'B', CHN),
  q('nq47', 'Infant Mortality Rate (IMR) measures deaths of infants:', 'Under 28 days per 1000 live births', 'Under 1 year per 1000 live births', 'Under 5 years per 1000 population', 'Under 1 year per 1000 total population', 'B', CHN),
  q('nq48', 'Minimum number of antenatal visits recommended under Indian National guidelines:', '2 visits', '4 visits', '6 visits', '8 visits', 'B', CHN),
  q('nq49', 'The MOST commonly used indicator of nutritional status in children under 5 in India:', 'Height-for-age', 'Weight-for-age (underweight)', 'Weight-for-height', 'Mid-upper arm circumference', 'B', CHN),
  q('nq50', 'Mantoux tuberculin skin test is read at:', '24 hours', '48–72 hours', '72–96 hours', '5–7 days', 'B', CHN),
  q('nq51', 'BCG vaccine is administered by which route?', 'Intramuscular', 'Subcutaneous', 'Intradermal', 'Oral', 'C', CHN),
  q('nq52', 'ASHA (Accredited Social Health Activist) primarily functions as:', 'A specialist community nurse', 'A bridge between the community and the formal health system', 'The in-charge of a Primary Health Centre', 'A trainer for auxiliary nurse midwives', 'B', CHN),
  q('nq53', "Under India's National Immunization Schedule (NIS), the DPT primary series is given at:", '6, 10, and 14 weeks of age', '2, 4, and 6 months of age', '4, 8, and 12 weeks of age', '6, 8, and 12 months of age', 'A', CHN),
  q('nq54', 'An epidemic is defined as:', 'A disease present at constant levels in a community at all times', 'A disease occurring in an unusually high number in a community at a specific time', 'A disease geographically limited to one small region', 'A disease spreading simultaneously across multiple countries', 'B', CHN),
  q('nq55', 'Crude Death Rate (CDR) is expressed as:', 'Deaths per 100 live births', 'Deaths per 1000 total mid-year population', 'Deaths per 1000 live births', 'Deaths per 100 total population', 'B', CHN),
  q('nq56', "Leprosy (Hansen's disease) is caused by:", 'Mycobacterium tuberculosis', 'Mycobacterium leprae', 'Treponema pallidum', 'Clostridium tetani', 'B', CHN),
  q('nq57', 'The "index case" in epidemiology refers to:', 'The most severely ill case in the outbreak', 'The first identified case in an outbreak', 'The most infectious case', 'The case with the greatest number of contacts', 'B', CHN),
  q('nq58', 'The vector responsible for transmitting Plasmodium falciparum malaria is:', 'Female Anopheles mosquito', 'Female Culex mosquito', 'Female Aedes mosquito', 'Female Mansonia mosquito', 'A', CHN),
  q('nq59', 'According to WHO, anaemia in pregnancy is defined as haemoglobin below:', '9 g/dL', '10 g/dL', '11 g/dL', '12 g/dL', 'C', CHN),
  q('nq60', 'Mid-Day Meal (MDM) scheme in India primarily targets:', 'Pregnant and lactating women', 'School children (Classes 1–8)', 'Infants under 2 years of age', 'Elderly population above 60 years', 'B', CHN),

  // ── Section D: OBG & Midwifery (Q61–Q80) ──
  q('nq61', "According to Nagele's rule, the Expected Date of Delivery (EDD) is calculated by adding to the FIRST day of LMP:", '7 days and 9 months', '14 days and 9 months', '7 days and 10 months', '14 days and 8 months', 'A', OBG),
  q('nq62', 'Normal duration of the FIRST stage of labour in a primigravida is:', '6–8 hours', '8–12 hours', '12–18 hours', '18–24 hours', 'C', OBG),
  q('nq63', 'APGAR score is assessed at:', '1 and 5 minutes after birth', '2 and 5 minutes after birth', '1 and 3 minutes after birth', '5 and 10 minutes after birth', 'A', OBG),
  q('nq64', 'Which of the following is NOT a component of the APGAR score?', 'Heart rate', 'Respiratory effort', 'Blood pressure', 'Reflex irritability', 'C', OBG),
  q('nq65', 'Normal fetal heart rate (FHR) during active labour is:', '100–120 bpm', '120–160 bpm', '160–180 bpm', '80–100 bpm', 'B', OBG),
  q('nq66', 'Preeclampsia is defined as BP ≥140/90 mmHg after 20 weeks of gestation PLUS:', 'Proteinuria (≥300 mg/24 h)', 'Pitting pedal oedema', 'Frontal headache', 'Visual disturbances', 'A', OBG),
  q('nq67', "Bishop's score is used to assess:", 'Fetal presentation and lie', 'Estimated fetal weight', 'Cervical favourability for induction of labour', 'Risk of postpartum haemorrhage', 'C', OBG),
  q('nq68', 'Periconceptional folic acid supplementation primarily prevents:', 'Iron-deficiency anaemia', 'Neural tube defects', 'Gestational diabetes', 'Placenta praevia', 'B', OBG),
  q('nq69', 'Lochia rubra (red lochia) typically lasts for:', '1–2 days', '3–4 days', '7–10 days', '10–14 days', 'B', OBG),
  q('nq70', 'The MOST common cause of primary postpartum haemorrhage (PPH) is:', 'Retained placenta', 'Uterine atony', 'Genital tract trauma', 'Coagulopathy', 'B', OBG),
  q('nq71', 'Colostrum is produced for the first:', '24 hours post delivery', '2–3 days post delivery', '5–7 days post delivery', '1–2 weeks post delivery', 'B', OBG),
  q('nq72', 'McRoberts manoeuvre is used to manage:', 'Breech delivery', 'Shoulder dystocia', 'Face presentation', 'Cord prolapse', 'B', OBG),
  q('nq73', 'Rh immunoglobulin (Anti-D) is given to Rh-negative pregnant women:', 'Only after delivery of an Rh-positive baby', 'At 28 weeks gestation AND after delivery of an Rh-positive baby', 'Only after spontaneous miscarriage', 'At 20 weeks gestation only', 'B', OBG),
  q('nq74', 'Normal blood loss during an uncomplicated vaginal delivery is:', 'Less than 200 mL', 'Less than 300 mL', 'Less than 500 mL', 'Less than 800 mL', 'C', OBG),
  q('nq75', 'The MOST reliable sign of true (established) labour is:', 'Lightening (descent of fetal head)', 'Bloody show', 'Progressive cervical dilation with effacement', 'Spontaneous rupture of membranes', 'C', OBG),
  q('nq76', 'Normal gestational age for a TERM pregnancy is:', '34–36 completed weeks', '36–40 completed weeks', '37–42 completed weeks', '38–41 completed weeks', 'C', OBG),
  q('nq77', 'Uterine involution is usually complete by:', '2 weeks postpartum', '4 weeks postpartum', '6 weeks postpartum', '8 weeks postpartum', 'C', OBG),
  q('nq78', 'The FIRST nursing priority in obstetric haemorrhagic shock is:', 'Administer blood transfusion immediately', 'Start IV oxytocin infusion', 'Secure two large-bore IV lines, lay patient flat, summon help', 'Perform uterine massage bimanually', 'C', OBG),
  q('nq79', 'The position MOST commonly used for vaginal delivery in hospital settings is:', "Left lateral (Sims') position", 'Knee-chest position', 'Dorsal lithotomy position', 'Squatting position', 'C', OBG),
  q('nq80', "A Bishop's score of ≥8 indicates:", 'Unfavourable cervix — induction not recommended', 'Favourable cervix — suitable for induction of labour', 'Cephalopelvic disproportion', 'Need for caesarean section', 'B', OBG),

  // ── Section E: Paediatric Nursing (Q81–Q100) ──
  q('nq81', 'Normal birth weight of a healthy full-term newborn is:', '2.0–2.5 kg', '2.5–3.5 kg', '3.5–4.5 kg', '4.0–5.0 kg', 'B', PDR),
  q('nq82', 'Normal heart rate of a newborn (0–28 days) is:', '80–100 bpm', '100–120 bpm', '120–160 bpm', '160–180 bpm', 'C', PDR),
  q('nq83', 'The anterior fontanelle in a healthy infant normally closes at:', '6–8 months', '9–12 months', '12–18 months', '18–24 months', 'C', PDR),
  q('nq84', 'A healthy infant doubles its birth weight by approximately:', '3 months', '5 months', '6 months', '9 months', 'B', PDR),
  q('nq85', 'The first primary (deciduous) tooth erupts at approximately:', '4 months', '6 months', '9 months', '12 months', 'B', PDR),
  q('nq86', 'Normal respiratory rate in a newborn (0–28 days) is:', '12–20 breaths/min', '20–30 breaths/min', '30–60 breaths/min', '60–80 breaths/min', 'C', PDR),
  q('nq87', 'Febrile seizures are MOST common in which age group?', '0–6 months (neonatal period)', '6 months – 5 years', '5–10 years', '10–15 years', 'B', PDR),
  q('nq88', 'DPT vaccine is CONTRAINDICATED in a child who previously had:', 'Mild fever after a prior dose', 'Anaphylaxis or severe allergic reaction to a prior dose', 'Loose stools at the time of vaccination', 'An upper respiratory tract infection', 'B', PDR),
  q('nq89', 'Normal occipitofrontal head circumference of a healthy term newborn is:', '28–30 cm', '33–35 cm', '36–38 cm', '38–40 cm', 'B', PDR),
  q('nq90', 'Pyloric stenosis in infants characteristically presents with:', 'Bilious (green) vomiting', 'Non-bilious, forceful projectile vomiting', 'Bloody diarrhoea', 'Constipation and abdominal distension', 'B', PDR),
  q('nq91', 'Down syndrome (Trisomy 21) is associated with a total chromosome count of:', '44', '45', '46', '47', 'D', PDR),
  q('nq92', "Koplik's spots on the buccal mucosa are PATHOGNOMONIC of:", 'Chickenpox (Varicella)', 'Mumps', 'Measles (Rubeola)', 'Rubella', 'C', PDR),
  q('nq93', 'BCG vaccination is CONTRAINDICATED in:', 'Premature infants', 'Symptomatic HIV-positive infants', 'Infants with neonatal jaundice', 'Low-birth-weight infants (>1500 g)', 'B', PDR),
  q('nq94', 'Intussusception in infants characteristically presents with:', 'Bilious vomiting and abdominal distension', 'Colicky abdominal pain and "currant jelly" stools', 'High-grade fever and bloody diarrhoea', 'Constipation and ribbon-shaped stools', 'B', PDR),
  q('nq95', 'Acute epiglottitis in children is MOST commonly caused by:', 'Streptococcus pyogenes', 'Haemophilus influenzae type B', 'Staphylococcus aureus', 'Streptococcus pneumoniae', 'B', PDR),
  q('nq96', 'A child with suspected epiglottitis should be placed in:', 'Supine with legs elevated', 'Prone position', 'Sitting upright (tripod position)', 'Left lateral position', 'C', PDR),
  q('nq97', "Under India's National Immunization Schedule, the first dose of MMR vaccine is given at:", '6 months', '9 months', '12 months', '18 months', 'B', PDR),
  q('nq98', 'The MOST common cause of bacterial meningitis in unvaccinated children under 2 years is:', 'Neisseria meningitidis', 'Streptococcus pneumoniae', 'Haemophilus influenzae type B', 'Group B Streptococcus', 'C', PDR),
  q('nq99', 'Club foot (Talipes equinovarus) is MOST effectively treated by:', 'Surgical correction alone', 'Serial casting using the Ponseti method', 'Bracing and splinting only', 'Observation until walking age', 'B', PDR),
  q('nq100','Normal venous blood glucose in a term newborn is:', '1.0–1.5 mmol/L', '1.5–2.0 mmol/L', '2.5–5.5 mmol/L', '5.5–7.0 mmol/L', 'C', PDR),
]
